## Section-2: Tensor Operations Fundamentals

### **Tensor Transposition**

**Tensor Transposition** is the process of rearranging (or permuting) the axes/dimensions of a tensor.

It’s the higher-dimensional generalization of **matrix transposition**.

---

### 1. **Matrix Transposition (2D case)**

* A **matrix** is a 2D tensor with shape `(rows, columns)`.
* Transposing swaps its two dimensions:

  $$
  A^T_{ij} = A_{ji}
  $$

  If $A$ has shape $(m, n)$, then $A^T$ has shape $(n, m)$.

Example:

$$
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}^T
=
\begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix}
$$

---

### 2. **Tensor Transposition (n-D case)**

* A **tensor** can have more than 2 dimensions, e.g., 3D: `(depth, height, width)` or `(channels, height, width)`.
* **Tensor transposition** means **reordering the dimensions** in a specified way.
* In notation, this is often called **permutation of axes**.

If $T$ has shape `(D₁, D₂, D₃)`, then:

* A transpose with order `(1, 0, 2)` swaps the first two axes.
* A transpose with order `(2, 0, 1)` moves the last axis to the front.

Mathematically, for a tensor $A$ with components $A_{i_1, i_2, \dots, i_n}$:

$$
\text{transpose}(A, \text{perm})_{j_1, j_2, \dots, j_n} = A_{i_{\text{perm}(1)}, i_{\text{perm}(2)}, \dots, i_{\text{perm}(n)}}
$$

where `perm` is the permutation order.

---

### 3. **Example**

Suppose $T$ has shape `(2, 3, 4)`:

* Original axes: `(0, 1, 2)` → shape `(2, 3, 4)`
* After `transpose(1, 0, 2)` → shape `(3, 2, 4)`
* After `transpose(2, 1, 0)` → shape `(4, 3, 2)`

In **NumPy**:

```python
import numpy as np

T = np.random.randint(0, 10, (2, 3, 4))
T1 = np.transpose(T, (1, 0, 2))  # swap axes 0 and 1
print(T.shape)   # (2, 3, 4)
print(T1.shape)  # (3, 2, 4)
```

---

### 4. **Why Tensor Transposition is Important**

* **Deep Learning**: Changing data layout for operations (e.g., `channels_first` ↔ `channels_last` in CNNs).
* **Linear Algebra**: Converting between row-major and column-major forms.
* **Data Manipulation**: Preparing tensors for broadcasting, concatenation, or reshaping.
* **Performance Optimization**: Some hardware prefers specific memory layouts.

### 1. Matrix Transposition (2D Tensor)

In [1]:
# Numpy
import numpy as np

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6]])

print("Original (NumPy):\n", A)
print("Transpose (NumPy):\n", A.T)

Original (NumPy):
 [[1 2 3]
 [4 5 6]]
Transpose (NumPy):
 [[1 4]
 [2 5]
 [3 6]]


In [3]:
# PyTorch
import torch

In [4]:
B = torch.tensor([[1, 2, 3], [4, 5, 6]])

print("Original (PyTorch):\n", B)
print("Transpose (PyTorch):\n", B.T)   # or torch.transpose(B, 0, 1)

Original (PyTorch):
 tensor([[1, 2, 3],
        [4, 5, 6]])
Transpose (PyTorch):
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


### 2. Swap Axes in a 3D Tensor

In [5]:
# NumPy
T = np.random.randint(0, 10, (2, 3, 4))
print(T)
print("Shape before:", T.shape)

[[[8 4 2 6]
  [3 8 4 6]
  [6 0 3 2]]

 [[7 5 4 3]
  [6 4 9 8]
  [8 8 9 3]]]
Shape before: (2, 3, 4)


In [6]:
T1 = np.transpose(T, (1, 0, 2))  # swap axis 0 and 1
print(T1)
print("Shape after (NumPy):", T1.shape)

[[[8 4 2 6]
  [7 5 4 3]]

 [[3 8 4 6]
  [6 4 9 8]]

 [[6 0 3 2]
  [8 8 9 3]]]
Shape after (NumPy): (3, 2, 4)


In [7]:
# PyTorch
T_torch = torch.randint(0, 10, (2, 3, 4))
print(T_torch)
print("Shape before:", T_torch.shape)

tensor([[[4, 1, 4, 4],
         [5, 3, 9, 0],
         [8, 7, 4, 3]],

        [[7, 1, 9, 0],
         [4, 0, 8, 5],
         [7, 1, 3, 4]]])
Shape before: torch.Size([2, 3, 4])


In [8]:
T1_torch = T_torch.permute(1, 0, 2)  # same operation
print(T1_torch)
print("Shape after (PyTorch):", T1_torch.shape)

tensor([[[4, 1, 4, 4],
         [7, 1, 9, 0]],

        [[5, 3, 9, 0],
         [4, 0, 8, 5]],

        [[8, 7, 4, 3],
         [7, 1, 3, 4]]])
Shape after (PyTorch): torch.Size([3, 2, 4])


### 3. Moving Last Axis to First (Channel Conversion)

In [9]:
# NumPy
img = np.random.rand(32, 32, 3)   # HWC (Height, Width, Channels)
chw_img = np.transpose(img, (2, 0, 1))  # to CHW
print("NumPy shape:", img.shape, "->", chw_img.shape)

NumPy shape: (32, 32, 3) -> (3, 32, 32)


In [10]:
# PyTorch
img_torch = torch.rand(32, 32, 3)  # HWC
chw_img_torch = img_torch.permute(2, 0, 1)  # to CHW
print("PyTorch shape:", img_torch.shape, "->", chw_img_torch.shape)

PyTorch shape: torch.Size([32, 32, 3]) -> torch.Size([3, 32, 32])


### 4. Batch of Matrices Transpose (4D Tensor)

In [11]:
# NumPy
batch = np.random.rand(10, 28, 28, 1)  # (batch, H, W, C)
batch_T = np.transpose(batch, (0, 3, 1, 2))  # (batch, C, H, W)
print("NumPy shape:", batch.shape, "->", batch_T.shape)

NumPy shape: (10, 28, 28, 1) -> (10, 1, 28, 28)


In [12]:
# PyTorch
batch_torch = torch.rand(10, 28, 28, 1)
batch_T_torch = batch_torch.permute(0, 3, 1, 2)
print("PyTorch shape:", batch_torch.shape, "->", batch_T_torch.shape)

PyTorch shape: torch.Size([10, 28, 28, 1]) -> torch.Size([10, 1, 28, 28])


### 5. Swapping Two Specific Dimensions in a Higher Tensor

In [13]:
# NumPy
X = np.random.rand(4, 5, 6, 7)
X_swap = np.swapaxes(X, 1, 2)  # swap axis-1 and axis-2
print("NumPy shape:", X.shape, "->", X_swap.shape)

NumPy shape: (4, 5, 6, 7) -> (4, 6, 5, 7)


In [14]:
# PyTorch
X_torch = torch.rand(4, 5, 6, 7)
X_swap_torch = torch.transpose(X_torch, 1, 2)  # swap dim-1 and dim-2
print("PyTorch shape:", X_torch.shape, "->", X_swap_torch.shape)

PyTorch shape: torch.Size([4, 5, 6, 7]) -> torch.Size([4, 6, 5, 7])
