## Section-2: Tensor Operations Fundamentals

### **Tensor Transposition**

**Tensor Transposition** is the process of rearranging (or permuting) the axes/dimensions of a tensor.

It’s the higher-dimensional generalization of **matrix transposition**.

---

### 1. **Matrix Transposition (2D case)**

* A **matrix** is a 2D tensor with shape `(rows, columns)`.
* Transposing swaps its two dimensions:

  $$
  A^T_{ij} = A_{ji}
  $$

  If $A$ has shape $(m, n)$, then $A^T$ has shape $(n, m)$.

Example:

$$
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}^T
=
\begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix}
$$

---

### 2. **Tensor Transposition (n-D case)**

* A **tensor** can have more than 2 dimensions, e.g., 3D: `(depth, height, width)` or `(channels, height, width)`.
* **Tensor transposition** means **reordering the dimensions** in a specified way.
* In notation, this is often called **permutation of axes**.

If $T$ has shape `(D₁, D₂, D₃)`, then:

* A transpose with order `(1, 0, 2)` swaps the first two axes.
* A transpose with order `(2, 0, 1)` moves the last axis to the front.

Mathematically, for a tensor $A$ with components $A_{i_1, i_2, \dots, i_n}$:

$$
\text{transpose}(A, \text{perm})_{j_1, j_2, \dots, j_n} = A_{i_{\text{perm}(1)}, i_{\text{perm}(2)}, \dots, i_{\text{perm}(n)}}
$$

where `perm` is the permutation order.

---

### 3. **Example**

Suppose $T$ has shape `(2, 3, 4)`:

* Original axes: `(0, 1, 2)` → shape `(2, 3, 4)`
* After `transpose(1, 0, 2)` → shape `(3, 2, 4)`
* After `transpose(2, 1, 0)` → shape `(4, 3, 2)`

In **NumPy**:

```python
import numpy as np

T = np.random.randint(0, 10, (2, 3, 4))
T1 = np.transpose(T, (1, 0, 2))  # swap axes 0 and 1
print(T.shape)   # (2, 3, 4)
print(T1.shape)  # (3, 2, 4)
```

---

### 4. **Why Tensor Transposition is Important**

* **Deep Learning**: Changing data layout for operations (e.g., `channels_first` ↔ `channels_last` in CNNs).
* **Linear Algebra**: Converting between row-major and column-major forms.
* **Data Manipulation**: Preparing tensors for broadcasting, concatenation, or reshaping.
* **Performance Optimization**: Some hardware prefers specific memory layouts.

### 1. Matrix Transposition (2D Tensor)

In [1]:
# Numpy
import numpy as np

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6]])

print("Original (NumPy):\n", A)
print("Transpose (NumPy):\n", A.T)

Original (NumPy):
 [[1 2 3]
 [4 5 6]]
Transpose (NumPy):
 [[1 4]
 [2 5]
 [3 6]]


In [3]:
# PyTorch
import torch

In [4]:
B = torch.tensor([[1, 2, 3], [4, 5, 6]])

print("Original (PyTorch):\n", B)
print("Transpose (PyTorch):\n", B.T)   # or torch.transpose(B, 0, 1)

Original (PyTorch):
 tensor([[1, 2, 3],
        [4, 5, 6]])
Transpose (PyTorch):
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


### 2. Swap Axes in a 3D Tensor

In [5]:
# NumPy
T = np.random.randint(0, 10, (2, 3, 4))
print(T)
print("Shape before:", T.shape)

[[[5 7 4 6]
  [7 3 0 1]
  [5 9 3 6]]

 [[2 0 7 7]
  [1 0 4 6]
  [8 8 7 1]]]
Shape before: (2, 3, 4)


In [6]:
T1 = np.transpose(T, (1, 0, 2))  # swap axis 0 and 1
print(T1)
print("Shape after (NumPy):", T1.shape)

[[[5 7 4 6]
  [2 0 7 7]]

 [[7 3 0 1]
  [1 0 4 6]]

 [[5 9 3 6]
  [8 8 7 1]]]
Shape after (NumPy): (3, 2, 4)


In [7]:
# PyTorch
T_torch = torch.randint(0, 10, (2, 3, 4))
print(T_torch)
print("Shape before:", T_torch.shape)

tensor([[[4, 0, 1, 6],
         [4, 7, 5, 5],
         [8, 2, 7, 9]],

        [[1, 0, 3, 4],
         [3, 6, 3, 7],
         [5, 0, 3, 2]]])
Shape before: torch.Size([2, 3, 4])


In [8]:
T1_torch = T_torch.permute(1, 0, 2)  # same operation
print(T1_torch)
print("Shape after (PyTorch):", T1_torch.shape)

tensor([[[4, 0, 1, 6],
         [1, 0, 3, 4]],

        [[4, 7, 5, 5],
         [3, 6, 3, 7]],

        [[8, 2, 7, 9],
         [5, 0, 3, 2]]])
Shape after (PyTorch): torch.Size([3, 2, 4])


### 3. Moving Last Axis to First (Channel Conversion)

In [9]:
# NumPy
img = np.random.rand(32, 32, 3)   # HWC (Height, Width, Channels)
chw_img = np.transpose(img, (2, 0, 1))  # to CHW
print("NumPy shape:", img.shape, "->", chw_img.shape)

NumPy shape: (32, 32, 3) -> (3, 32, 32)


In [10]:
# PyTorch
img_torch = torch.rand(32, 32, 3)  # HWC
chw_img_torch = img_torch.permute(2, 0, 1)  # to CHW
print("PyTorch shape:", img_torch.shape, "->", chw_img_torch.shape)

PyTorch shape: torch.Size([32, 32, 3]) -> torch.Size([3, 32, 32])


### 4. Batch of Matrices Transpose (4D Tensor)

In [11]:
# NumPy
batch = np.random.rand(10, 28, 28, 1)  # (batch, H, W, C)
batch_T = np.transpose(batch, (0, 3, 1, 2))  # (batch, C, H, W)
print("NumPy shape:", batch.shape, "->", batch_T.shape)

NumPy shape: (10, 28, 28, 1) -> (10, 1, 28, 28)


In [12]:
# PyTorch
batch_torch = torch.rand(10, 28, 28, 1)
batch_T_torch = batch_torch.permute(0, 3, 1, 2)
print("PyTorch shape:", batch_torch.shape, "->", batch_T_torch.shape)

PyTorch shape: torch.Size([10, 28, 28, 1]) -> torch.Size([10, 1, 28, 28])


### 5. Swapping Two Specific Dimensions in a Higher Tensor

In [13]:
# NumPy
X = np.random.rand(4, 5, 6, 7)
X_swap = np.swapaxes(X, 1, 2)  # swap axis-1 and axis-2
print("NumPy shape:", X.shape, "->", X_swap.shape)

NumPy shape: (4, 5, 6, 7) -> (4, 6, 5, 7)


In [14]:
# PyTorch
X_torch = torch.rand(4, 5, 6, 7)
X_swap_torch = torch.transpose(X_torch, 1, 2)  # swap dim-1 and dim-2
print("PyTorch shape:", X_torch.shape, "->", X_swap_torch.shape)

PyTorch shape: torch.Size([4, 5, 6, 7]) -> torch.Size([4, 6, 5, 7])


# **Introduction to Basic Tensor Arithmetical Properties**

Tensors are the fundamental data structures used in modern scientific computing, machine learning, and deep learning. A tensor can be thought of as a generalized form of scalars, vectors, and matrices that can extend to any number of dimensions. Since they generalize familiar mathematical objects, tensors naturally inherit a rich set of **arithmetical properties**.

Just as numbers, vectors, and matrices follow certain arithmetic rules—such as commutativity of addition, distributivity of multiplication, and the existence of identity elements—tensors also obey these properties. Understanding these rules is important because they guarantee consistency when performing operations like tensor addition, scalar multiplication, elementwise multiplication, and transposition. These properties form the **building blocks** for more advanced concepts in linear algebra, numerical computation, and deep learning frameworks like NumPy and PyTorch.

At the most basic level, tensor arithmetic is performed **elementwise** (for addition and multiplication) or **structurally** (for operations like transpose). For example, when two tensors of the same shape are added, the operation applies entry by entry. Similarly, transposing a tensor rearranges its axes, but still preserves key algebraic properties such as $(A + B)^T = A^T + B^T$.

By studying these properties, we gain a solid foundation that allows us to:

* Manipulate tensors confidently in code (NumPy, PyTorch).
* Simplify mathematical expressions in linear algebra.
* Ensure correctness when designing deep learning models.
* Build intuition for higher-level operations like matrix multiplication, broadcasting, and tensor contractions.

In the following sections, we will explore the most important **basic tensor arithmetical properties**—including addition, scalar multiplication, elementwise multiplication, and transpose rules—using simple **2D tensors (matrices)** in NumPy and PyTorch.

## ✅ **Agenda:**

1. Commutativity of addition
2. Associativity of addition
3. Additive identity (zero tensor)
4. Additive inverse
5. Scalar identity (1)
6. Scalar zero (0)
7. Associativity of scalar multiplication
8. Distributivity of scalar multiplication over addition
9. Commutativity of elementwise multiplication
10. Distributivity of elementwise multiplication
11. Transpose of transpose
12. Transpose of sum
13. Transpose of scalar multiplication
14. Transpose of elementwise product

# 📘 **Basic Tensor Arithmetical Properties**

Let’s start with **example tensors**:

In [15]:
# NumPy
import numpy as np
A = np.arange(1, 13).reshape(3, 4)  # 3x4 tensor
B = np.ones((3, 4), dtype=int) * 2
C = np.full((3, 4), 3)

In [16]:
# PyTorch
import torch
A_t = torch.arange(1, 13).reshape(3, 4)
B_t = torch.ones((3, 4), dtype=torch.int32) * 2
C_t = torch.full((3, 4), 3)

In [17]:
print(A)
print(B)
print(C)

print(A_t)
print(B_t)
print(C_t)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]], dtype=torch.int32)
tensor([[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]])


So we have:

$$
A =
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12
\end{bmatrix},
\quad
B =
\begin{bmatrix}
2 & 2 & 2 & 2 \\
2 & 2 & 2 & 2 \\
2 & 2 & 2 & 2
\end{bmatrix},
\quad
C =
\begin{bmatrix}
3 & 3 & 3 & 3 \\
3 & 3 & 3 & 3 \\
3 & 3 & 3 & 3
\end{bmatrix}
$$

## **1. Addition is Commutative**

$$
A + B = B + A
$$

In [18]:
print("NumPy:\n", A + B, "\n", B + A)
print("PyTorch:\n", A_t + B_t, "\n", B_t + A_t)

NumPy:
 [[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]] 
 [[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
PyTorch:
 tensor([[ 3,  4,  5,  6],
        [ 7,  8,  9, 10],
        [11, 12, 13, 14]]) 
 tensor([[ 3,  4,  5,  6],
        [ 7,  8,  9, 10],
        [11, 12, 13, 14]])


## **2. Addition is Associative**

$$
(A + B) + C = A + (B + C)
$$

In [19]:
print("NumPy:\n", (A + B) + C, "\n", A + (B + C))
print("PyTorch:\n", (A_t + B_t) + C_t, "\n", A_t + (B_t + C_t))

NumPy:
 [[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]] 
 [[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
PyTorch:
 tensor([[ 6,  7,  8,  9],
        [10, 11, 12, 13],
        [14, 15, 16, 17]]) 
 tensor([[ 6,  7,  8,  9],
        [10, 11, 12, 13],
        [14, 15, 16, 17]])


## **3. Zero Element (Additive Identity)**

$$
A + 0 = A
$$

In [20]:
Z = np.zeros((3, 4), dtype=int)
print("NumPy:\n", A + Z)

Z_t = torch.zeros((3, 4), dtype=torch.int32)
print("PyTorch:\n", A_t + Z_t)

NumPy:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
PyTorch:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


## **4. Additive Inverse**

$$
A + (-A) = 0
$$

In [21]:
print("NumPy:\n", A + (-A))
print("PyTorch:\n", A_t + (-A_t))

NumPy:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
PyTorch:
 tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


## **5. Scalar Multiplication Identity**

$$
1 \cdot A = A
$$

In [22]:
print("NumPy:\n", 1 * A)
print("PyTorch:\n", 1 * A_t)

NumPy:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
PyTorch:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


## **6. Multiplication by Zero**

$$
0 \cdot A = 0
$$

In [23]:
print("NumPy:\n", 0 * A)
print("PyTorch:\n", 0 * A_t)

NumPy:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
PyTorch:
 tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


## **7. Scalar Multiplication is Associative**

$$
(\alpha \beta) A = \alpha (\beta A)
$$

In [24]:
alpha, beta = 2, 3
print("NumPy:\n", (alpha * beta) * A, "\n", alpha * (beta * A))
print("PyTorch:\n", (alpha * beta) * A_t, "\n", alpha * (beta * A_t))

NumPy:
 [[ 6 12 18 24]
 [30 36 42 48]
 [54 60 66 72]] 
 [[ 6 12 18 24]
 [30 36 42 48]
 [54 60 66 72]]
PyTorch:
 tensor([[ 6, 12, 18, 24],
        [30, 36, 42, 48],
        [54, 60, 66, 72]]) 
 tensor([[ 6, 12, 18, 24],
        [30, 36, 42, 48],
        [54, 60, 66, 72]])


## **8. Scalar Multiplication Distributes Over Addition**

$$
\alpha (A + B) = \alpha A + \alpha B
$$

In [25]:
alpha = 5
print("NumPy:\n", alpha * (A + B), "\n", alpha * A + alpha * B)
print("PyTorch:\n", alpha * (A_t + B_t), "\n", alpha * A_t + alpha * B_t)

NumPy:
 [[15 20 25 30]
 [35 40 45 50]
 [55 60 65 70]] 
 [[15 20 25 30]
 [35 40 45 50]
 [55 60 65 70]]
PyTorch:
 tensor([[15, 20, 25, 30],
        [35, 40, 45, 50],
        [55, 60, 65, 70]]) 
 tensor([[15, 20, 25, 30],
        [35, 40, 45, 50],
        [55, 60, 65, 70]])


## **9. Elementwise Multiplication is Commutative**

$$
A \odot B = B \odot A
$$

In [26]:
print("NumPy:\n", A * B, "\n", B * A)
print("PyTorch:\n", A_t * B_t, "\n", B_t * A_t)

NumPy:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]] 
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
PyTorch:
 tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]]) 
 tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])


## **10. Elementwise Multiplication Distributes Over Addition**

$$
A \odot (B + C) = A \odot B + A \odot C
$$

In [27]:
print("NumPy:\n", A * (B + C), "\n", A * B + A * C)
print("PyTorch:\n", A_t * (B_t + C_t), "\n", A_t * B_t + A_t * C_t)

NumPy:
 [[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]] 
 [[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]
PyTorch:
 tensor([[ 5, 10, 15, 20],
        [25, 30, 35, 40],
        [45, 50, 55, 60]]) 
 tensor([[ 5, 10, 15, 20],
        [25, 30, 35, 40],
        [45, 50, 55, 60]])


## **11. Transpose of Transpose**

$$
(A^T)^T = A
$$

In [28]:
print("NumPy:\n", (A.T).T)
print("PyTorch:\n", (A_t.T).T)

NumPy:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
PyTorch:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


## **12. Transpose of Sum**

$$
(A + B)^T = A^T + B^T
$$

In [29]:
print("NumPy:\n", (A + B).T, "\n", A.T + B.T)
print("PyTorch:\n", (A_t + B_t).T, "\n", A_t.T + B_t.T)

NumPy:
 [[ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]
 [ 6 10 14]] 
 [[ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]
 [ 6 10 14]]
PyTorch:
 tensor([[ 3,  7, 11],
        [ 4,  8, 12],
        [ 5,  9, 13],
        [ 6, 10, 14]]) 
 tensor([[ 3,  7, 11],
        [ 4,  8, 12],
        [ 5,  9, 13],
        [ 6, 10, 14]])


## **13. Transpose of Scalar Multiple**

$$
(\alpha A)^T = \alpha A^T
$$

In [30]:
alpha = 4
print("NumPy:\n", (alpha * A).T, "\n", alpha * (A.T))
print("PyTorch:\n", (alpha * A_t).T, "\n", alpha * (A_t.T))

NumPy:
 [[ 4 20 36]
 [ 8 24 40]
 [12 28 44]
 [16 32 48]] 
 [[ 4 20 36]
 [ 8 24 40]
 [12 28 44]
 [16 32 48]]
PyTorch:
 tensor([[ 4, 20, 36],
        [ 8, 24, 40],
        [12, 28, 44],
        [16, 32, 48]]) 
 tensor([[ 4, 20, 36],
        [ 8, 24, 40],
        [12, 28, 44],
        [16, 32, 48]])


## **14. Transpose of Elementwise Product**

$$
(A \odot B)^T = A^T \odot B^T
$$

In [31]:
print("NumPy:\n", (A * B).T, "\n", A.T * B.T)
print("PyTorch:\n", (A_t * B_t).T, "\n", A_t.T * B_t.T)

NumPy:
 [[ 2 10 18]
 [ 4 12 20]
 [ 6 14 22]
 [ 8 16 24]] 
 [[ 2 10 18]
 [ 4 12 20]
 [ 6 14 22]
 [ 8 16 24]]
PyTorch:
 tensor([[ 2, 10, 18],
        [ 4, 12, 20],
        [ 6, 14, 22],
        [ 8, 16, 24]]) 
 tensor([[ 2, 10, 18],
        [ 4, 12, 20],
        [ 6, 14, 22],
        [ 8, 16, 24]])


# **What is Tensor Reduction?**

**Tensor Reduction** refers to the process of **reducing a tensor along one or more dimensions (axes)** by applying an operation such as **sum, mean, max, min, product, etc.**

Instead of keeping the full tensor, we “reduce” its dimensionality by aggregating values.

---

## **1. Intuition**

* Suppose we have a **2D tensor (matrix)**:

$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$$

* **Full reduction (no axis specified):**
  Sum of all elements → $1+2+\dots+9 = 45$
  Mean of all elements → $\frac{45}{9} = 5$

* **Reduction along axis 0 (rows):**
  Collapse rows → column-wise operation

  $$
  \text{sum}(A, \text{axis}=0) = [12, 15, 18]
  $$

* **Reduction along axis 1 (columns):**
  Collapse columns → row-wise operation

  $$
  \text{sum}(A, \text{axis}=1) = [6, 15, 24]
  $$

👉 In short: **Reduction shrinks dimensions by aggregating values.**

---

## **2. Common Reduction Operations**

### Reduction Operations You Can Perform:

1. **Sum** (`sum`, `reduce_sum`)
2. **Mean** (`mean`, `reduce_mean`)
3. **Max / Min** (`max`, `reduce_max`, `min`, `reduce_min`)
4. **Product** (`prod`, `reduce_prod`)
5. **Argmax / Argmin** (indices of extrema)
6. **Std / Variance** (`std`, `var`, `reduce_std`, `reduce_variance`)
7. **Any / All** (logical reductions)

## 📘 **Example Tensor**

In [32]:
import numpy as np
import torch
import tensorflow as tf

In [33]:
# NumPy
A_np = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# PyTorch
A_torch = torch.tensor([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])

# TensorFlow
A_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])


## **1. Sum Reduction**

In [34]:
# NumPy
print("NumPy Sum (all):", np.sum(A_np))  
print("NumPy Sum axis=0:", np.sum(A_np, axis=0))  
print("NumPy Sum axis=1:", np.sum(A_np, axis=1))  

# PyTorch
print("PyTorch Sum (all):", torch.sum(A_torch))  
print("PyTorch Sum dim=0:", torch.sum(A_torch, dim=0))  
print("PyTorch Sum dim=1:", torch.sum(A_torch, dim=1))  

# TensorFlow
print("TF Sum (all):", tf.reduce_sum(A_tf).numpy())  
print("TF Sum axis=0:", tf.reduce_sum(A_tf, axis=0).numpy())  
print("TF Sum axis=1:", tf.reduce_sum(A_tf, axis=1).numpy())  

NumPy Sum (all): 45
NumPy Sum axis=0: [12 15 18]
NumPy Sum axis=1: [ 6 15 24]
PyTorch Sum (all): tensor(45)
PyTorch Sum dim=0: tensor([12, 15, 18])
PyTorch Sum dim=1: tensor([ 6, 15, 24])
TF Sum (all): 45
TF Sum axis=0: [12 15 18]
TF Sum axis=1: [ 6 15 24]


## **2. Mean Reduction**

In [35]:
# NumPy
print("NumPy Mean (all):", np.mean(A_np))  
print("NumPy Mean axis=0:", np.mean(A_np, axis=0))  
print("NumPy Mean axis=1:", np.mean(A_np, axis=1))  

# PyTorch
print("PyTorch Mean (all):", torch.mean(A_torch.float()))  
print("PyTorch Mean dim=0:", torch.mean(A_torch.float(), dim=0))  
print("PyTorch Mean dim=1:", torch.mean(A_torch.float(), dim=1))  

# TensorFlow
print("TF Mean (all):", tf.reduce_mean(A_tf).numpy())  
print("TF Mean axis=0:", tf.reduce_mean(A_tf, axis=0).numpy())  
print("TF Mean axis=1:", tf.reduce_mean(A_tf, axis=1).numpy())  


NumPy Mean (all): 5.0
NumPy Mean axis=0: [4. 5. 6.]
NumPy Mean axis=1: [2. 5. 8.]
PyTorch Mean (all): tensor(5.)
PyTorch Mean dim=0: tensor([4., 5., 6.])
PyTorch Mean dim=1: tensor([2., 5., 8.])
TF Mean (all): 5
TF Mean axis=0: [4 5 6]
TF Mean axis=1: [2 5 8]


## **3. Max Reduction**

In [36]:
# NumPy
print("NumPy Max (all):", np.max(A_np))  
print("NumPy Max axis=0:", np.max(A_np, axis=0))  
print("NumPy Max axis=1:", np.max(A_np, axis=1))  

# PyTorch
print("PyTorch Max (all):", torch.max(A_torch))  
print("PyTorch Max dim=0:", torch.max(A_torch, dim=0))  
print("PyTorch Max dim=1:", torch.max(A_torch, dim=1))  

# TensorFlow
print("TF Max (all):", tf.reduce_max(A_tf).numpy())  
print("TF Max axis=0:", tf.reduce_max(A_tf, axis=0).numpy())  
print("TF Max axis=1:", tf.reduce_max(A_tf, axis=1).numpy())  


NumPy Max (all): 9
NumPy Max axis=0: [7 8 9]
NumPy Max axis=1: [3 6 9]
PyTorch Max (all): tensor(9)
PyTorch Max dim=0: torch.return_types.max(
values=tensor([7, 8, 9]),
indices=tensor([2, 2, 2]))
PyTorch Max dim=1: torch.return_types.max(
values=tensor([3, 6, 9]),
indices=tensor([2, 2, 2]))
TF Max (all): 9
TF Max axis=0: [7 8 9]
TF Max axis=1: [3 6 9]


## **4. Min Reduction**

In [37]:
# NumPy
print("NumPy Min (all):", np.min(A_np))  
print("NumPy Min axis=0:", np.min(A_np, axis=0))  
print("NumPy Min axis=1:", np.min(A_np, axis=1))  

# PyTorch
print("PyTorch Min (all):", torch.min(A_torch))  
print("PyTorch Min dim=0:", torch.min(A_torch, dim=0))  
print("PyTorch Min dim=1:", torch.min(A_torch, dim=1))  

# TensorFlow
print("TF Min (all):", tf.reduce_min(A_tf).numpy())  
print("TF Min axis=0:", tf.reduce_min(A_tf, axis=0).numpy())  
print("TF Min axis=1:", tf.reduce_min(A_tf, axis=1).numpy())  


NumPy Min (all): 1
NumPy Min axis=0: [1 2 3]
NumPy Min axis=1: [1 4 7]
PyTorch Min (all): tensor(1)
PyTorch Min dim=0: torch.return_types.min(
values=tensor([1, 2, 3]),
indices=tensor([0, 0, 0]))
PyTorch Min dim=1: torch.return_types.min(
values=tensor([1, 4, 7]),
indices=tensor([0, 0, 0]))
TF Min (all): 1
TF Min axis=0: [1 2 3]
TF Min axis=1: [1 4 7]


## **5. Product Reduction**

In [38]:
# NumPy
print("NumPy Prod (all):", np.prod(A_np))  
print("NumPy Prod axis=0:", np.prod(A_np, axis=0))  
print("NumPy Prod axis=1:", np.prod(A_np, axis=1))  

# PyTorch
print("PyTorch Prod (all):", torch.prod(A_torch))  
print("PyTorch Prod dim=0:", torch.prod(A_torch, dim=0))  
print("PyTorch Prod dim=1:", torch.prod(A_torch, dim=1))  

# TensorFlow
print("TF Prod (all):", tf.reduce_prod(A_tf).numpy())  
print("TF Prod axis=0:", tf.reduce_prod(A_tf, axis=0).numpy())  
print("TF Prod axis=1:", tf.reduce_prod(A_tf, axis=1).numpy())  


NumPy Prod (all): 362880
NumPy Prod axis=0: [ 28  80 162]
NumPy Prod axis=1: [  6 120 504]
PyTorch Prod (all): tensor(362880)
PyTorch Prod dim=0: tensor([ 28,  80, 162])
PyTorch Prod dim=1: tensor([  6, 120, 504])
TF Prod (all): 362880
TF Prod axis=0: [ 28  80 162]
TF Prod axis=1: [  6 120 504]


## **6. Argmax (Index of Max)**

In [39]:
# NumPy
print("NumPy Argmax (all):", np.argmax(A_np))  
print("NumPy Argmax axis=0:", np.argmax(A_np, axis=0))  
print("NumPy Argmax axis=1:", np.argmax(A_np, axis=1))  

# PyTorch
print("PyTorch Argmax (all):", torch.argmax(A_torch))  
print("PyTorch Argmax dim=0:", torch.argmax(A_torch, dim=0))  
print("PyTorch Argmax dim=1:", torch.argmax(A_torch, dim=1))  

# TensorFlow
print("TF Argmax axis=0:", tf.argmax(A_tf, axis=0).numpy())  
print("TF Argmax axis=1:", tf.argmax(A_tf, axis=1).numpy())  


NumPy Argmax (all): 8
NumPy Argmax axis=0: [2 2 2]
NumPy Argmax axis=1: [2 2 2]
PyTorch Argmax (all): tensor(8)
PyTorch Argmax dim=0: tensor([2, 2, 2])
PyTorch Argmax dim=1: tensor([2, 2, 2])
TF Argmax axis=0: [2 2 2]
TF Argmax axis=1: [2 2 2]


## **7. Argmin (Index of Min)**

In [40]:
# NumPy
print("NumPy Argmin (all):", np.argmin(A_np))  
print("NumPy Argmin axis=0:", np.argmin(A_np, axis=0))  
print("NumPy Argmin axis=1:", np.argmin(A_np, axis=1))  

# PyTorch
print("PyTorch Argmin (all):", torch.argmin(A_torch))  
print("PyTorch Argmin dim=0:", torch.argmin(A_torch, dim=0))  
print("PyTorch Argmin dim=1:", torch.argmin(A_torch, dim=1))  

# TensorFlow
print("TF Argmin axis=0:", tf.argmin(A_tf, axis=0).numpy())  
print("TF Argmin axis=1:", tf.argmin(A_tf, axis=1).numpy())  


NumPy Argmin (all): 0
NumPy Argmin axis=0: [0 0 0]
NumPy Argmin axis=1: [0 0 0]
PyTorch Argmin (all): tensor(0)
PyTorch Argmin dim=0: tensor([0, 0, 0])
PyTorch Argmin dim=1: tensor([0, 0, 0])
TF Argmin axis=0: [0 0 0]
TF Argmin axis=1: [0 0 0]


## **8. Standard Deviation & Variance**

In [41]:
# NumPy
print("NumPy Std (all):", np.std(A_np))  
print("NumPy Var (all):", np.var(A_np))  

# PyTorch
print("PyTorch Std (all):", torch.std(A_torch.float()))  
print("PyTorch Var (all):", torch.var(A_torch.float()))  

# TensorFlow
print("TF Std (all):", tf.math.reduce_std(tf.cast(A_tf, tf.float32)).numpy())  
print("TF Var (all):", tf.math.reduce_variance(tf.cast(A_tf, tf.float32)).numpy())  


NumPy Std (all): 2.581988897471611
NumPy Var (all): 6.666666666666667
PyTorch Std (all): tensor(2.7386)
PyTorch Var (all): tensor(7.5000)
TF Std (all): 2.5819888
TF Var (all): 6.6666665


## **9. Logical Reductions (any, all)**

In [42]:
# NumPy
print("NumPy Any:", np.any(A_np > 5))  
print("NumPy All:", np.all(A_np < 0))  

# PyTorch
print("PyTorch Any:", torch.any(A_torch > 5))  
print("PyTorch All:", torch.all(A_torch > 0))  

# TensorFlow
print("TF Any:", tf.reduce_any(A_tf > 5).numpy())  
print("TF All:", tf.reduce_all(A_tf > 0).numpy())  


NumPy Any: True
NumPy All: False
PyTorch Any: tensor(True)
PyTorch All: tensor(True)
TF Any: True
TF All: True
